name: 'Add Comment'
description: 'Add a comment on a PR'
author: 's-tuli'
inputs:
  pull_number:  # id of input
    description: 'pull_number'
    required: true
    default: 3
  repo-token:  # id of input
    description: 'repo token'
    required: true  
runs:
  using: 'node12'
  main: 'Final.js'
