name: PRFlow Bikes

on: 
  pull_request:
    branches:
    - master
    paths:
    - actions/AddComment/**  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@master
    - uses: s-tuli/githubactioncomment/actions/AddComment@master
      with:        
        pull_number: '2'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
